// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsGHUys_aNNLRKVA17iIFs7nCroTI_9rQ',
    appId: '1:1025008658003:web:e6d528da50f0254431c8a6',
    messagingSenderId: '1025008658003',
    projectId: 'hydsmartfire',
    authDomain: 'hydsmartfire.firebaseapp.com',
    storageBucket: 'hydsmartfire.firebasestorage.app',
    measurementId: 'G-YYQHKQHT9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Ilg2sQexL3NKPRLwDZqOXKiHR4W-Sfk',
    appId: '1:859177258327:android:985402f4ede30b3a660212',
    messagingSenderId: '859177258327',
    projectId: 'back-up-hydroponic',
    storageBucket: 'back-up-hydroponic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB_oAhdppNmQpGjpicZvqhFciQc3XvC7c',
    appId: '1:859177258327:ios:2fa1769cedc6d090660212',
    messagingSenderId: '859177258327',
    projectId: 'back-up-hydroponic',
    storageBucket: 'back-up-hydroponic.firebasestorage.app',
    iosBundleId: 'com.example.hydSmartApp',
  );

}